# Generated by Django 3.1.5 on 2021-01-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Тип услуги', 'verbose_name_plural': 'Тип услуги'},
        ),
        migrations.RemoveField(
            model_name='services',
            name='types',
        ),
        migrations.AddField(
            model_name='services',
            name='service',
            field=models.CharField(default='', max_length=80, unique=True, verbose_name='Типы услуг'),
        ),
        migrations.DeleteModel(
            name='Types',
        ),
    ]
