# Generated by Django 3.1.5 on 2021-01-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210115_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='fio_client',
            field=models.CharField(max_length=70, verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='fio_staff',
            field=models.CharField(max_length=70, verbose_name='ФИО сотрудника'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='service_name',
            field=models.CharField(max_length=70, verbose_name='услуга'),
        ),
    ]
